### ISSUE TITLE
A syntax to improve in readme file

### ISSUE THREAD

**Issue by victorbartel** [dex4er/js-promise-socket#2]
Hi,

For Typescript you propose to declare your module as:
```typescript
import * as net 'net'
import { PromiseSocket } as 'promise-socket'
```
But you forgot to put `from` instruction. So it should be:
```typescript
import * as net from "net";
import PromiseSocket from "promise-socket";
```

**Comment by dex4er** [comment]
For what version of promise-socket? I checked at https://www.npmjs.com/package/promise-socket and there is

```ts
import PromiseSocket from 'promise-socket'
```

in README.

And it should be:

```ts
import net from 'net'
```

because this "star" notation is now obsoleted. See `--esModuleInterop` options for Typescript compiler.
