### ISSUE TITLE
Module '"net"' has no default export

### ISSUE THREAD

**Issue by dustinlacewell** [dex4er/js-promise-socket#4]
I am trying to use promise-socket within a VSCode extension and when I attempt to compile it I get the following errors from `tsc`:

```
tsc -p ./

node_modules/promise-socket/lib/promise-socket.d.ts:3:8 - error TS1192: Module '"net"' has no default export.

3 import net from 'net'
         ~~~

node_modules/promise-socket/lib/promise-socket.d.ts:7:78 - error TS2344: Type 'TSocket' does not satisfy the constraintnode_modules/promise-socket/lib/promise-socket.d.ts:7:78 - error TS2344: Type 'TSocket' does not satisfy the constraint 'Duplex'.

7 export class PromiseSocket<TSocket extends net.Socket> extends PromiseDuplex<TSocket> {
                                                                               ~~~~~~~


Found 2 errors.
```

**Comment by kevinramharak** [comment]
Can you post your `tsconfig.json` file? Do you have `@types/node` installed? What NodeJS version are you using?

It seems like just a compiler error.

**Comment by dex4er** [comment]
Please check if you have

```json
{
  "compilerOptions": {
    "esModuleInterop": true
 }
```

in your `tsconfig.json`. This syntax is perfectly legal with TypeScript >= 2.7 and you can check on Travis CI https://travis-ci.org/dex4er/js-promise-socket that example scripts like https://github.com/dex4er/js-promise-socket/blob/master/examples/simple-http-client-ts.ts are compiled correctly.
