### ISSUE TITLE
TypeError: PromiseSocket is not a constructor

### ISSUE THREAD

**Issue by pritisolanki** [dex4er/js-promise-socket#5]
Hi,

Following the documentation

When using const promiseSocket = new PromiseSocket(socket) It throws error - TypeError: PromiseSocket is not a constructor

Best

**Comment by kevinramharak** [comment]
Can you post some code on how you import the library?
When installing with npm like `npm install promise-socket`
and then running the code below it seems to work fine.
```ts
import PromiseSocket from 'promise-socket'

const promiseSocket = new PromiseSocket();
```

**Comment by dex4er** [comment]
@pritisolanki Documentation is clear:

_Javascript_:

```js
const {PromiseSocket} = require('promise-socket')
```

_Typescript_:

```ts
import PromiseSocket from 'promise-socket'
```

It is because Typescript can use the default exported symbol so you don't need to unpack `PromiseSocket` explicitly. In pure Javascript you can also write:

```js
const PromiseSocket = require('promise-socket').PromiseSocket
```

or

```js
const PromiseSocket = require('promise-socket').default
```
