### ISSUE TITLE
ECONNREFUSED When trying to bind to a legitimate socket 

### ISSUE THREAD

**Issue by notthelewis** [dex4er/js-promise-socket#65]
I have used the promise wrapper to write a client for the system I'm building, and quite liked the interface. So, I decided to convert the existing server to use this same package.

However, in doing so, I ran into an issue which I can't wrap my head around. 

Firstly, let's take a bog standard net server:
```
require('dotenv').config({path: '../.env'});
const net = require('net');
const server = net.createServer();
server.listen(process.env.PORT);
```

This is a working snippet, and binds to the right port which I can telnet into. There's a bunch more going on behind the scenes, but this is the bit of functionality I can't get to work using PromiseSockets.

```
require('dotenv').config({path: '../.env'});

const net = require('net');
const {PromiseSocket} = require('promise-socket');
const socket = new net.Socket();
const promiseSocket = new PromiseSocket(socket);

async function main()
{
    try {
        await promiseSocket.connect(1523, 'localhost');
    } catch(e) {
        console.log(e)
    }
}

main();
```

But I receive the error message:

```
Error: connect ECONNREFUSED 127.0.0.1:1523
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 1523
}
```
I'm using `"promise-socket" : "7.00" `

Again, I can bind to this socket fine- and have tried numerous things to get this working. Is this an issue my end or yours? Thanks!

**Comment by dex4er** [comment]
This is really odd. The error is pretty clear: no listening socket on 127.0.0.1 port 1523. Maybe you started the server on another machine? Or maybe just start the server or explicit 127.0.0.1 rather than implicit ipv6 address?

**Comment by dex4er** [comment]
I can't reproduce your problem in my environment (Ubuntu 20.04.2 LTS on Windows 10 x86_64; Node 16.0.0; your scripts)

**Comment by notthelewis** [comment]
Thanks for getting back to me.

I'm also on Ubuntu 20.04.2, though I haven't had the chance to test this on a Windows machine. 
npm: `v7.7.6`
node `v14.15.1`

I know for a fact the port isn't bound elsewhere, I know this as I ran:

`lsof -i -n | grep :1523` - The result is blank when run as non-root and root user(s). `ss -antlp | grep :1523`  also reports nothing.... The port is 100% not used anywhere. To further prove this, I can bind to that very same port using any other application- for example I used the regular JS Net package, and I used a C server to bind and listen also.

I hoisted the exact code into a different directory elsewhere, to check whether other dependencies were potentially causing an issue... This does not appear to be the case, as it didn't work there either. 

Is this library capable of running server applications, or is it simply for wrapping clients? I can't find any instance in the documentation RE the usage of this package for server-side promise wrapping,  and so I fear that I may have wasted some time trying to get it to do something it wasn't designed to do. 

Please find my complete package-lock.json
```
{
  "name": "promSock",
  "version": "1.0.0",
  "lockfileVersion": 2,
  "requires": true,
  "packages": {
    "": {
      "version": "1.0.0",
      "license": "ISC",
      "dependencies": {
        "promise-socket": "^7.0.0"
      }
    },
    "node_modules/core-js": {
      "version": "3.11.0",
      "resolved": "https://registry.npmjs.org/core-js/-/core-js-3.11.0.tgz",
      "integrity": "sha512-bd79DPpx+1Ilh9+30aT5O1sgpQd4Ttg8oqkqi51ZzhedMM1omD2e6IOF48Z/DzDCZ2svp49tN/3vneTK6ZBkXw==",
      "hasInstallScript": true,
      "funding": {
        "type": "opencollective",
        "url": "https://opencollective.com/core-js"
      }
    },
    "node_modules/promise-duplex": {
      "version": "6.0.0",
      "resolved": "https://registry.npmjs.org/promise-duplex/-/promise-duplex-6.0.0.tgz",
      "integrity": "sha512-ZL7rquzjTFzInDBeWYcsT+qddolNvzigahk6MI6qLSbQvlyRRCJkU3JztgaVunzvkH28smRa2Qu/cY9RXtSkgA==",
      "dependencies": {
        "core-js": "^3.6.5",
        "promise-readable": "^6.0.0",
        "promise-writable": "^6.0.0"
      },
      "engines": {
        "node": ">=10.0.0"
      }
    },
    "node_modules/promise-readable": {
      "version": "6.0.0",
      "resolved": "https://registry.npmjs.org/promise-readable/-/promise-readable-6.0.0.tgz",
      "integrity": "sha512-5NxtmUswijvX5cAM0zPSy6yiCXH/eKBpiiBq6JfAUrmngMquMbzcBhF2qA+ocs4rYYKdvAfv3cOvZxADLtL1CA==",
      "dependencies": {
        "core-js": "^3.6.5"
      },
      "engines": {
        "node": ">=10.0.0"
      }
    },
    "node_modules/promise-socket": {
      "version": "7.0.0",
      "resolved": "https://registry.npmjs.org/promise-socket/-/promise-socket-7.0.0.tgz",
      "integrity": "sha512-Oic9BrxmcHOPEnzKp2Js+ehFyvsbd0WxsE5khweCTHuRvdzbXjHUZmSDT6F9TW8SIkAJ0lCzoHjMYnb0WQJPiw==",
      "dependencies": {
        "promise-duplex": "^6.0.0",
        "tslib": "^2.0.1"
      },
      "engines": {
        "node": ">=10.0.0"
      }
    },
    "node_modules/promise-writable": {
      "version": "6.0.0",
      "resolved": "https://registry.npmjs.org/promise-writable/-/promise-writable-6.0.0.tgz",
      "integrity": "sha512-b81zre/itgJFS7dwWzIdKNVVqvLiUxYRS/wolUB0H1YY/tAaS146XGKa4Q/5wCbsnXLyn0MCeV6f8HHe4iUHLg==",
      "engines": {
        "node": ">=10.0.0"
      }
    },
    "node_modules/tslib": {
      "version": "2.2.0",
      "resolved": "https://registry.npmjs.org/tslib/-/tslib-2.2.0.tgz",
      "integrity": "sha512-gS9GVHRU+RGn5KQM2rllAlR3dU6m7AcpJKdtH8gFvQiC4Otgk98XnmMU+nZenHt/+VhnBPWwgrJsyrdcw6i23w=="
    }
  },
  "dependencies": {
    "core-js": {
      "version": "3.11.0",
      "resolved": "https://registry.npmjs.org/core-js/-/core-js-3.11.0.tgz",
      "integrity": "sha512-bd79DPpx+1Ilh9+30aT5O1sgpQd4Ttg8oqkqi51ZzhedMM1omD2e6IOF48Z/DzDCZ2svp49tN/3vneTK6ZBkXw=="
    },
    "promise-duplex": {
      "version": "6.0.0",
      "resolved": "https://registry.npmjs.org/promise-duplex/-/promise-duplex-6.0.0.tgz",
      "integrity": "sha512-ZL7rquzjTFzInDBeWYcsT+qddolNvzigahk6MI6qLSbQvlyRRCJkU3JztgaVunzvkH28smRa2Qu/cY9RXtSkgA==",
      "requires": {
        "core-js": "^3.6.5",
        "promise-readable": "^6.0.0",
        "promise-writable": "^6.0.0"
      }
    },
    "promise-readable": {
      "version": "6.0.0",
      "resolved": "https://registry.npmjs.org/promise-readable/-/promise-readable-6.0.0.tgz",
      "integrity": "sha512-5NxtmUswijvX5cAM0zPSy6yiCXH/eKBpiiBq6JfAUrmngMquMbzcBhF2qA+ocs4rYYKdvAfv3cOvZxADLtL1CA==",
      "requires": {
        "core-js": "^3.6.5"
      }
    },
    "promise-socket": {
      "version": "7.0.0",
      "resolved": "https://registry.npmjs.org/promise-socket/-/promise-socket-7.0.0.tgz",
      "integrity": "sha512-Oic9BrxmcHOPEnzKp2Js+ehFyvsbd0WxsE5khweCTHuRvdzbXjHUZmSDT6F9TW8SIkAJ0lCzoHjMYnb0WQJPiw==",
      "requires": {
        "promise-duplex": "^6.0.0",
        "tslib": "^2.0.1"
      }
    },
    "promise-writable": {
      "version": "6.0.0",
      "resolved": "https://registry.npmjs.org/promise-writable/-/promise-writable-6.0.0.tgz",
      "integrity": "sha512-b81zre/itgJFS7dwWzIdKNVVqvLiUxYRS/wolUB0H1YY/tAaS146XGKa4Q/5wCbsnXLyn0MCeV6f8HHe4iUHLg=="
    },
    "tslib": {
      "version": "2.2.0",
      "resolved": "https://registry.npmjs.org/tslib/-/tslib-2.2.0.tgz",
      "integrity": "sha512-gS9GVHRU+RGn5KQM2rllAlR3dU6m7AcpJKdtH8gFvQiC4Otgk98XnmMU+nZenHt/+VhnBPWwgrJsyrdcw6i23w=="
    }
  }
}

```

**Comment by notthelewis** [comment]
P.S. Noticed that my node version was a little out of date. I updated it to now use v16.0.0, and the error is still there :disappointed:

**Comment by dex4er** [comment]
> `ss -antlp | grep :1523` also reports nothing.... 

What do you mean "reports nothing"? Empty results? Then nothing is listening on this port. Maybe you forgot to set PORT envvar or your dotenv file is incorrect.

If you use native Ubuntu then 100% should be ok. Ubuntu on Windows with WSL might behave a little differently because of networking is isolated like in ie. Docker.

Version of Node is not important. This module works with Node >= 6.0

**Comment by notthelewis** [comment]
I meant that the ss command reports nothing as in it simply replies with a newline, thus indicating nothing is bound to that port... I wrote a small promise wrapper myself so that I can progress further, and I know for a definitive fact that the port is available for use. The environment variable cannot be the issue, as I don't even use it in that snippet. I hard-coded the value 1523 as I suspected it might be the env var. I still get the same, pervasive error message- preventing me from writing a TCP **endpoint** using this promise wrapper.

I'm running native Ubuntu 20.04.2, and I can confirm that the above snippet (even with the dotenv require commented out, as it's not being used in this case) - definitely does not work on my machine.

**Comment by dex4er** [comment]
So for me:

```sh
PORT=1523 node server.js
```

and 
```sh
node client.js
```

where server and client are from your snipped. And output for `ss`:

```
$  ss -antlp
State          Recv-Q         Send-Q                 Local Address:Port                  Peer Address:Port        Process
LISTEN         0              511                                *:1523                             *:*            users:(("node",pid=29015,fd=18))
LISTEN         0              511                                *:39151                            *:*            users:(("node",pid=17409,fd=18))
```

so everything as expected. I'm afraid your issue is not related to NodeJS at all.

Are you sure you don't have any local firewall that drops connections? Or loopback interface is shut down.

**Comment by notthelewis** [comment]
I apologise for describing this issue badly. I was trying to use PromiseSocket to actually host the server, not connect to an existing host.

Anyway, It is possible to wrap the *server* connections using the promise socket, I was just not binding/listening to them.

Please see the following  example of working server-side PromiseSockets, and thank you for taking the time to diagnose this non-issue.

```

require('dotenv').config();

const net = require('net');
const {PromiseSocket} = require('promise-socket');
const server = net.createServer();

/* This bit is where I was getting confused. I thought that the bind and listen were handled in the connect call with promise-socket.. */
server.on('connection', handleConnection);
server.listen(process.env.PORT);

async function handleConnection(socket)
{
    /* Once connection is received from client, then wrap it in a socket connection. */
    const promiseSocket = new PromiseSocket(socket);
    while (true) { 
        const chunk = await promiseSocket.read(8); // Read 8 bytes
        console.log(chunk.toString().toUpperCase()); 
        await promiseSocket.write(chunk.toString().toUpperCase()); // Send 'em back uppercase.
    }
}
```

**Comment by dex4er** [comment]
So your example works for me. I mean I can bind the socket and connect it ie. with `telnet`.

But please note you have to detect EOF. In this case either chunk will be `undefined` or its length will be lesser than expected.

**Comment by notthelewis** [comment]
Thank you for coming back to me. How would one go about detecting EOF using PromiseSocket?
