### ISSUE TITLE
Add the returned this ftom setTimeout()

### ISSUE THREAD

**Issue by yhojann-cl** [dex4er/js-promise-socket#72]
Please, return `this` object into `setTimeout` function, by example:

```javascript
await (new PromiseSocket(client))
    .setTimeout(options.timeout)
    .connect({ host: options.host, port: options.port })
    .then(() => {
         ....
```

Current result:

> TypeError: Cannot read property 'connect' of undefined

**Comment by dex4er** [comment]
Fixed in https://github.com/dex4er/js-promise-socket/releases/tag/v8.0.0
